---
fail_on_violations: true
ruby:
  config_file: .rubocop.yml
haml:
  config_file: .haml-lint.yml
scss:
  config_file: .scss-lint.yml
jshint:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc
