sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- bundle exec rubocop
- bundle-audit update
- bundle-audit
- brakeman --run-all-checks --exit-on-warn .
- bundle exec rspec spec
