language: ruby
bundler_args: "--without development"
sudo: false
cache: bundler
rvm:
- 2.3.1
before_script:
- RAILS_ENV=test bundle exec rake db:create db:schema:load
script:
- bundle exec rubocop
- bundle exec bundle-audit update
- bundle exec bundle-audit
- bundle exec rspec spec
