sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
script:
- bundle exec rake db:create
- bundle exec rake db:migrate --trace
- bundle exec rubocop
# - brakeman --run-all-checks --exit-on-warn .
- bundle exec bundle-audit update
- bundle exec bundle-audit
- bundle exec rspec spec
