language: ruby
bundler_args: --without development
cache: bundler
rvm:
- 2.1.3
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
- cp config/database.yml.example config/database.yml
- RAILS_ENV=test bundle exec rake db:create db:schema:load
script:
- bundle exec rspec
